services:
  garage:
    image: dxflrs/garage:v0.9.0
    container_name: garage_datalake
    network_mode: "bridge"
    restart: unless-stopped
    command: /garage server
    environment:
      - GARAGE_CONFIG_FILE=/etc/garage.toml
    ports:
      - "3900:3900"
      - "3901:3901"
      - "3902:3902"
      - "3903:3903"
    volumes:
      - ./garage.toml:/etc/garage.toml:ro 
      - garage_meta:/var/lib/garage/meta
      - garage_data:/var/lib/garage/data

volumes:
  garage_meta:
  garage_data:
    # volumes:
    #   - ./garage.toml:/etc/garage.toml:ro 
    #   - ./data_datalake/garage/meta:/var/lib/garage/meta
    #   - ./data_datalake/garage/data:/var/lib/garage/data