[tool.poetry]
name = "certification"
version = "0.1.0"
description = ""
authors = ["Stéphanie Parcollet <st.parcollet@orange.fr>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
pandas = "^2.2.3"
numpy = "<2.0.0"
psycopg2-binary = "^2.9.10"
boto3 = "^1.42.33"
pymongo = "^4.16.0"
requests = "^2.32.5"
python-dotenv = "^1.2.1"
dbt-postgres = "^1.10.0"

[tool.poetry.group.app.dependencies]
python = "^3.12"
scrapy = "^2.12.0"
scrapy-impersonate = "^1.6.2"
dateparser = "^1.2.1"
azure-storage-file-datalake = "^12.20.0"
sqlalchemy = "^2.0.40"
streamlit = "^1.44.1"
pydantic = {extras = ["email"], version = "^2.12.5"}
fastapi = "^0.115.12"
uvicorn = "^0.34.2"
python-multipart = "^0.0.20"
pyjwt = "^2.10.1"
bcrypt = "4.0.1"
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
scrapy-playwright = "^0.0.46"
faker = "^40.5.1"
psutil = "^7.2.2"
graphviz = "^0.21"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
